apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "7daysdie.fullname" . }}
  labels:
{{ include "7daysdie.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "7daysdie.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "7daysdie.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      dnsConfig:
        options:
          - name: ndots
            value: "1"
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ template "7daysdie.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: SEVEN_DAYS_TO_DIE_CONFIG_FILE
              value: "/config/serverconfig.xml"
          ports:
            - name: sevendays-tcp-1
              containerPort: 26900
              protocol: TCP
            - name: sevendays-udp-1
              containerPort: 26900
              protocol: UDP
            - name: sevendays-udp-2
              containerPort: 26901
              protocol: UDP
            - name: sevendays-udp-3
              containerPort: 26902
              protocol: UDP
            - name: sevendays-adm-1
              containerPort: 8080
              protocol: TCP
            - name: sevendays-adm-2
              containerPort: 8081
              protocol: TCP
          volumeMounts:
            - name: data
              mountPath: /app/.local/share/7DaysToDie
            - name: config
              mountPath: /config
          #livenessProbe:
          #  httpGet:
          #    path: /
          #    port: http
          #readinessProbe:
          #  httpGet:
          #    path: /
          #    port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: config
          configMap:
            name: {{ template "7daysdie.fullname" . }}
        - name: data
        {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            {{- if .Values.persistence.existingClaim }}
            claimName: {{ .Values.persistence.existingClaim | quote }}
            {{- else }}
            claimName: {{ template "7daysdie.fullname" . }}
            {{- end }}
        {{- else }}
          emptyDir: {}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
