{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "7daysdie.serviceAccountName" . }}
  labels:
{{ include "7daysdie.labels" . | indent 4 }}
{{- end -}}
