apiVersion: v1
kind: Service
metadata:
  name: tcp-{{ include "sevendaysdie.fullname" . }}
  labels:
{{ include "sevendaysdie.labels" . | indent 4 }}
  annotations:
    metallb.universe.tf/allow-shared-ip: {{ include "sevendaysdie.fullname" . }}
{{- if .Values.service.annotations }}
{{ toYaml .Values.service.annotations | indent 4 }}
{{- end }}
spec:
  type: {{ .Values.service.type }}
  externalTrafficPolicy: {{ .Values.service.externalTrafficPolicy }}
  ports:
    - port: 26900
      targetPort: sevendays-tcp-1
      protocol: TCP
      name: sevendays-tcp-1
  selector:
    app.kubernetes.io/name: {{ include "sevendaysdie.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
---
apiVersion: v1
kind: Service
metadata:
  name: udp-{{ include "sevendaysdie.fullname" . }}
  labels:
{{ include "sevendaysdie.labels" . | indent 4 }}
  annotations:
    metallb.universe.tf/allow-shared-ip: {{ include "sevendaysdie.fullname" . }}
{{- if .Values.service.annotations }}
{{ toYaml .Values.service.annotations | indent 4 }}
{{- end }}
spec:
  type: {{ .Values.service.type }}
  externalTrafficPolicy: {{ .Values.service.externalTrafficPolicy }}
  ports:
    - port: 26900
      targetPort: sevendays-udp-1
      protocol: UDP
      name: sevendays-udp-1
    - port: 26901
      targetPort: sevendays-udp-2
      protocol: UDP
      name: sevendays-udp-2
    - port: 26902
      targetPort: sevendays-udp-3
      protocol: UDP
      name: sevendays-udp-3
  selector:
    app.kubernetes.io/name: {{ include "sevendaysdie.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
---
apiVersion: v1
kind: Service
metadata:
  name: adm-{{ include "sevendaysdie.fullname" . }}
  labels:
{{ include "sevendaysdie.labels" . | indent 4 }}
  annotations:
    metallb.universe.tf/allow-shared-ip: {{ include "sevendaysdie.fullname" . }}
{{- if .Values.service.annotations }}
{{ toYaml .Values.service.annotations | indent 4 }}
{{- end }}
spec:
  type: {{ .Values.service.type }}
  externalTrafficPolicy: {{ .Values.service.externalTrafficPolicy }}
  ports:
      # FIXME - move to new service so it can be optionally exposed
      # control port
    - port: 8080
      targetPort: sevendays-adm-1
      protocol: TCP
      name: sevendays-adm-1
      # FIXME - move to new service so it can be optionally exposed
      # telnet port
    - port: 8081
      targetPort: sevendays-adm-2
      protocol: TCP
      name: sevendays-adm-2
  selector:
    app.kubernetes.io/name: {{ include "sevendaysdie.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
---
